### ISSUE TITLE
Proxy stream without saving to disk (or limit size)

### ISSUE THREAD

**Issue by jshep321** [AngellusMortis/sxm-client#9]
* sxm-client version: .0.2.5
* Python version: 3.8.0
* Operating System: Ubuntu 20.04.6 LTS

### Description

I am trying to simply proxy and NOT archive any music to disk -- concerned about disk usage.  I would like the stream to be available to pull and listen to 24/7.

### What I Did
It seems impossible to avoid this -- when I set output folder to /dev/null I get an error.
from config file:  

```

output_folder: "/dev/null"
---
sxm_player.hls[1395989] INFO playing http://0.0.0.0:7944/radiomargaritaville.m3u8 (/dev/null/streams/radiomargaritaville.mp3)
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jshep321/.local/lib/python3.8/site-packages/sxm_player/runner.py", line 50, in worker_wrapper
    worker = worker_class(*args, **kwargs)
  File "/home/jshep321/.local/lib/python3.8/site-packages/sxm_player/workers/archiver.py", line 36, in __init__
    os.makedirs(self.stream_folder, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/dev/null/streams'
```

**Comment by jshep321** [comment]
Never mind.  I am using the included sxm binary for this.
